development:
  adapter: postgresql 
  encoding: unicode
  database: blog_dev
  pool: 5
  host: localhost  
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password']%>

development:
  adapter: postgresql 
  encoding: unicode
  database: blog_dev
  pool: 5
  host: localhost  
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password']%>

